version: '3.9'

services:
  api:
    container_name: tourabi-api
    build: .
    ports:
      - 8512:8502
    environment:
      HTTP_PORT: 8502
    networks:
      - mongodb_localhost

networks:
  mongodb_localhost:
    driver: bridge
